---
- include: playbooks/commands.yml
- include: playbooks/middleware.yml
- include: playbooks/wordpress.yml
- include: playbooks/mysql_compatibility.yml
- include: playbooks/php.yml 
  when: vccw.php_version != '7.0'

